package com.waitlist.ingestion.mapper;

import com.waitlist.ingestion.dto.request.SignupRequest;
import com.waitlist.ingestion.entity.WaitlistEntry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class SignupMapperTest {

    SignupMapper mapper;

    @BeforeEach
    void setUp() {
        mapper = new SignupMapperImpl();
    }

    @Test
    void toEntity_mapsNameAndCompany() {
        var req = new SignupRequest();
        req.setEmail("alice@example.com");
        req.setName("Alice");
        req.setCompany("Acme Corp");

        WaitlistEntry entity = mapper.toEntity(req);

        assertThat(entity.getName()).isEqualTo("Alice");
        assertThat(entity.getCompany()).isEqualTo("Acme Corp");
    }

    @Test
    void toEntity_referredByMapsFromReferralCode() {
        var req = new SignupRequest();
        req.setEmail("bob@example.com");
        req.setName("Bob");
        req.setReferralCode("abc12345");

        WaitlistEntry entity = mapper.toEntity(req);

        // referredBy <- request.referralCode (the referrer's code)
        assertThat(entity.getReferredBy()).isEqualTo("abc12345");
    }

    @Test
    void toEntity_emailIsIgnored_mustBeSetManually() {
        var req = new SignupRequest();
        req.setEmail("carol@example.com");
        req.setName("Carol");

        WaitlistEntry entity = mapper.toEntity(req);

        // Email is excluded from the mapping — service normalises and sets it
        assertThat(entity.getEmail()).isNull();
    }

    @Test
    void toEntity_referralCodeIsIgnored_mustBeSetManually() {
        var req = new SignupRequest();
        req.setEmail("dave@example.com");
        req.setReferralCode("someref1");

        WaitlistEntry entity = mapper.toEntity(req);

        // The entity's own referralCode is generated by the service, not copied from the request
        assertThat(entity.getReferralCode()).isNull();
    }

    @Test
    void toEntity_nullReferralCode_leavesReferredByNull() {
        var req = new SignupRequest();
        req.setEmail("eve@example.com");
        req.setName("Eve");
        req.setReferralCode(null);

        WaitlistEntry entity = mapper.toEntity(req);

        assertThat(entity.getReferredBy()).isNull();
    }

    @Test
    void toEntity_nullOptionalFields_remainNull() {
        var req = new SignupRequest();
        req.setEmail("frank@example.com");

        WaitlistEntry entity = mapper.toEntity(req);

        assertThat(entity.getName()).isNull();
        assertThat(entity.getCompany()).isNull();
        assertThat(entity.getReferredBy()).isNull();
    }
}
