package com.waitlist.ingestion.mapper;

import com.waitlist.ingestion.dto.request.SignupRequest;
import com.waitlist.ingestion.entity.WaitlistEntry;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Maps between the signup request DTO and the WaitlistEntry JPA entity.
 *
 * <p>Fields intentionally excluded from the mapping:
 * <ul>
 *   <li>{@code email} — normalised (lower-cased, trimmed) by the service before the entity is saved</li>
 *   <li>{@code referralCode} — a UUID snippet generated by the service, not supplied by the client</li>
 *   <li>{@code createdAt / updatedAt} — defaulted to {@code OffsetDateTime.now()} in the entity field declaration</li>
 *   <li>{@code version} — managed exclusively by JPA optimistic locking</li>
 *   <li>{@code id} — assigned by the DB on INSERT</li>
 * </ul>
 *
 * <p>{@code referredBy} is populated from the request's {@code referralCode} field, which
 * carries the <em>referrer's</em> code — i.e. "I was referred by the person with this code".
 */
@Mapper(componentModel = "spring")
public interface SignupMapper {

    @Mapping(target = "id",           ignore = true)
    @Mapping(target = "email",        ignore = true)
    @Mapping(target = "referralCode", ignore = true)
    @Mapping(target = "referredBy",   source = "referralCode")
    @Mapping(target = "createdAt",    ignore = true)
    @Mapping(target = "updatedAt",    ignore = true)
    @Mapping(target = "version",      ignore = true)
    WaitlistEntry toEntity(SignupRequest request);
}
